#!/usr/bin/env bash
set -Eeuo pipefail
requested_commit="${1:-}"; [[ "$requested_commit" =~ ^[0-9a-f]{40}$ ]] || { echo "Usage: $0 <40-character source commit>" >&2; exit 2; }
root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"; repo_root="$(cd -- "$root_dir/../.." && pwd)"; runtime_root="${BELT_DEPLOY_RUNTIME_ROOT:-/home/newadmin}"
resolved_commit="$(git -C "$repo_root" rev-parse --verify --quiet "${requested_commit}^{commit}")" || { echo "Unresolvable source commit: $requested_commit" >&2; exit 1; }; [[ "$resolved_commit" == "$requested_commit" ]] || { echo "Source commit did not resolve exactly" >&2; exit 1; }
source_tree="$(mktemp -d "${TMPDIR:-/tmp}/belt-verify.XXXXXX")"; trap 'rm -rf -- "$source_tree"' EXIT; git -C "$repo_root" archive --format=tar "$resolved_commit" | tar -x -C "$source_tree" || { echo "Could not materialize source commit" >&2; exit 1; }
declare -a rels=(ops/belt/multica-bridge.cjs ops/belt/guardrails.cjs ops/belt/parked-entry-audit.cjs ops/belt/parity/multica-relay-advance-daemon.cjs ops/belt/parity/relay-dead-rows.cjs ops/belt/multica-cicd-worker.cjs ops/belt/cicd-deploy-evidence.cjs ops/belt/belt-config-guard.sh ops/belt/multica-daemon-wrapper.sh ops/belt/ecosystem.gsp-belt.config.js ops/belt/multica-bundle.py ops/belt/RUNBOOK_SPEC_WORKER.md ops/belt/RUNBOOK_BUILD_WORKER.md ops/belt/RUNBOOK_QC_WORKER.md ops/belt/WORKER_COMMON.md)
declare -a targets=("$runtime_root/gsp-multica/multica-bridge.cjs" "$runtime_root/gsp-multica/guardrails.cjs" "$runtime_root/gsp-multica/parked-entry-audit.cjs" "$runtime_root/gsp-multica/parity/multica-relay-advance-daemon.cjs" "$runtime_root/gsp-multica/parity/relay-dead-rows.cjs" "$runtime_root/multica-cicd-worker.cjs" "$runtime_root/cicd-deploy-evidence.cjs" "$runtime_root/tools/belt-config-guard.sh" "$runtime_root/gsp-multica/fleet/multica-daemon-wrapper.sh" "$runtime_root/gsp-multica/fleet/ecosystem.gsp-belt.config.js" "$runtime_root/tools/multica-bundle.py" "$runtime_root/multica-doctrine/RUNBOOK_SPEC_WORKER.md" "$runtime_root/multica-doctrine/RUNBOOK_BUILD_WORKER.md" "$runtime_root/multica-doctrine/RUNBOOK_QC_WORKER.md" "$runtime_root/multica-doctrine/WORKER_COMMON.md")
status=0; for i in "${!rels[@]}"; do source_file="$source_tree/${rels[$i]}"; target_file="${targets[$i]}"; [[ -f "$source_file" ]] || { echo "Missing selected commit blob: ${rels[$i]}" >&2; status=1; continue; }; [[ -f "$target_file" ]] || { echo "Missing runtime file: $target_file" >&2; status=1; continue; }; cmp -s -- "$source_file" "$target_file" && echo "Match: $target_file" || { echo "Drift: $target_file" >&2; status=1; }; done; exit "$status"
